fix: make subscription plans editable again
Subscription plan creation worked because desired_num_licenses was
always non-null, but it's not possible to edit an existing plan (some of
them do have null values for desired_num_licenses) due to the following
error:

```
num_new_licenses = obj.desired_num_licenses - obj.num_licenses
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

ENT-8269